version: "3.9"
services:
  mysql1:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - "3306:3306"
    container_name: db2
    volumes:
      - ./dbfiles:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass123
